name: C/C++ CI

on: push

jobs:
  build:

    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        - {name: "Ubuntu", os: ubuntu-latest, cfg: sudo apt install -y libcurl4-openssl-dev zlib1g-dev libluajit-5.1-dev, build: ./build}
        - {name: "Windows", os: windows-latest, build: .\build.bat}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      with:
        path: core
    
    - name: Checkout base plugin
      uses: actions/checkout@v3
      with:
        repository: igor725/cs-base
        path: cs-base

    - name: Checkout Survival plugin
      uses: actions/checkout@v3
      with:
        repository: igor725/cs-survival
        path: cs-survival

    - name: Checkout Lua plugin
      uses: actions/checkout@v3
      with:
        repository: igor725/cs-lua
        path: cs-lua

    - name: Checkout WorldEdit plugin
      uses: actions/checkout@v3
      with:
        repository: igor725/cs-worldedit
        path: cs-worldedit

    - name: Detect MSVC
      uses: ilammy/msvc-dev-cmd@v1
      if: ${{matrix.config.name == 'Windows'}}

    - name: Configure
      if: ${{matrix.config.cfg != null}}
      run: ${{matrix.config.cfg}}

    - name: Build
      working-directory: core
      run: |
        ${{matrix.config.build}} wall dbg noprompt
        ${{matrix.config.build}} wall dbg pb base install
        ${{matrix.config.build}} wall dbg pb survival install
        ${{matrix.config.build}} wall dbg pb lua install
        ${{matrix.config.build}} wall dbg pb worldedit install

    # - name: Test
    #   run: ${{matrix.config.svbin}} testmode

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.config.name}}-${{github.sha}}
        path: |
          core/out
          !core/out/**/objs
