name: C/C++ CI

on: push

jobs:
  build:

    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        - {name: "Ubuntu", os: ubuntu-latest, cfg: sudo apt install -y libcurl4-openssl-dev zlib1g-dev, build: ./build, svbin: ./out/$(gcc -dumpmachine)/server}

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ${{matrix.config.cfg}}
    - name: build
      run: ${{matrix.config.build}} wall dbg
    # - name: test
    #   run: ${{matrix.config.svbin}} testmode
