name: C/C++ CI

on:
  push:
    paths:
      - src/**
      - .github/**

jobs:
  build:

    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Ubuntu x64
          os: ubuntu-latest
          arch: x86_64
          cfg: sudo apt install -y libcurl4-openssl-dev zlib1g-dev libluajit-5.1-dev
          build: ./build
          testbin: ./core/out/x86_64-linux-gnu/server

        - name: Ubuntu x86
          os: ubuntu-latest
          arch: i686
          cfg: |
            sudo dpkg --add-architecture i386
            sudo apt update
            sudo apt install -y gcc-i686-linux-gnu libcurl4-openssl-dev:i386 zlib1g-dev:i386 libluajit-5.1-dev:i386
          build: ./build
          testbin: ./core/out/i686-linux-gnu/server

        - name: Windows x64
          os: windows-latest
          arch: x86_64
          build: .\build.bat
          testbin: .\core\out\x64dbg\server.exe

        - name: Windows x86
          os: windows-latest
          arch: x86
          build: .\build.bat
          testbin: .\core\out\x86dbg\server.exe


    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      with:
        path: core
    
    - name: Checkout base plugin
      uses: actions/checkout@v3
      with:
        repository: igor725/cs-base
        path: cs-base

    - name: Checkout Survival plugin
      uses: actions/checkout@v3
      with:
        repository: igor725/cs-survival
        path: cs-survival

    - name: Checkout Lua plugin
      uses: actions/checkout@v3
      with:
        repository: igor725/cs-lua
        path: cs-lua

    - name: Checkout WorldEdit plugin
      uses: actions/checkout@v3
      with:
        repository: igor725/cs-worldedit
        path: cs-worldedit

    - name: Detect MSVC
      uses: ilammy/msvc-dev-cmd@v1
      if: ${{matrix.config.os == 'windows-latest'}}
      with:
        arch: ${{matrix.config.arch}}

    - name: Install some packages
      if: ${{matrix.config.cfg != null}}
      run: ${{matrix.config.cfg}}

    - name: Build core
      working-directory: core
      env:
        CC: ${{matrix.config.arch}}-linux-gnu-gcc
      run: |
        ${{matrix.config.build}} wall dbg noprompt

    - name: Build plugins
      working-directory: core
      env:
        CC: ${{matrix.config.arch}}-linux-gnu-gcc
      run: |
        ${{matrix.config.build}} wall dbg pb base install
        ${{matrix.config.build}} wall dbg pb survival install
        ${{matrix.config.build}} wall dbg pb lua install
        ${{matrix.config.build}} wall dbg pb worldedit install

    - name: Make some tests
      if: ${{matrix.config.testbin != null}}
      run: ${{matrix.config.testbin}} testmode

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cserver-${{matrix.config.os}}-${{matrix.config.arch}}
        path: |
          core/out
          !core/out/**/objs
          !core/out/**/worlds
          !core/out/**/configs
          !core/out/**/*.ilk
          !core/out/**/*.exp
